### ISSUE TITLE
Error when compling.

### ISSUE THREAD

**Issue by thunder-weasel** [freemed/tty0tty#12]
Thank you for this code, I've been using it for about a year, however, when building the module for my current kernel, I met with fail.
system: 4.11.7-1-ARCH #1 SMP PREEMPT Sat Jun 24 22:22:46 CDT 2017 x86_64 GNU/Linux
Error:
tty0tty-1.2/module/tty0tty.c:524:8: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
    if (signal_pending(current))
        ^~~~~~~~~~~~~~
        timer_pending
cc1: some warnings being treated as errors

After a solid two minutes of effort, the fix:
Add to includes in tty0tty.c:
#include <linux/sched/signal.h>

Thank you.

**Comment by zgyarmati** [comment]
PR #10 handles this
