### ISSUE TITLE
tiocmiwait ioctl is broken

### ISSUE THREAD

**Issue by jmerdich** [freemed/tty0tty#13]
The TIOCMIWAIT ioctl is dangerously broken. Presently, it will oops when issued, since the wait queue it uses isn't initialized, but even if that were fixed, it would never return (unless interrupted), since the places that are supposed to trigger the wait queue never actually wake it up! 

I'll be around with a patch set to fix.

**Comment by ReallyNiceGuy** [comment]
Any news on this patch?
