### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by Antonstr** [freemed/tty0tty#14]
Good day to you

I am trying to compile tty0tty on a BeagleBone Black 

I am experiencing the following problem when trying to compile
Could you please assist? 
Thank you in advance
Anton
root@arm:~/tty0tty/tty0tty-1.2/module# make
make -C /lib/modules/4.4.84-ti-r120/build M=/root/tty0tty/tty0tty-1.2/module modules
make[1]: *** /lib/modules/4.4.84-ti-r120/build: No such file or directory.  Stop.
Makefile:26: recipe for target 'default' failed
make: *** [default] Error 2
root@arm:~/tty0tty/tty0tty-1.2/module# cd tty0tty-1.2/module

Second attempt 

root@arm:~/tty0tty-1.2/module# make
make -C /lib/modules/4.4.84-ti-r120/build M=/root/tty0tty-1.2/module modules
make[1]: *** /lib/modules/4.4.84-ti-r120/build: No such file or directory.  Stop.
Makefile:26: recipe for target 'default' failed
make: *** [default] Error 2
root@arm:~/tty0tty-1.2/module#

**Comment by jbuchbinder** [comment]
It looks like you're missing build/source packages for your kernel version.
