### ISSUE TITLE
How to throttle writes according to input queue size of other paired port

### ISSUE THREAD

**Issue by cmcqueen** [freemed/tty0tty#2]
I have a scenario where the application connected to the other paired port can only read data at a certain rate (because it is passing it on to another slow hardware device). So I want to limit the number of bytes that can be written in one port, to ensure the other paired port's input data queue gets no bigger than, say, 64 bytes. So I want to modify `tty0tty_write_room()` function in the tty0tty module, so that it returns eg `[64 – the number of bytes in the other paired port's input queue]`.

I'm trying to figure out how to get the number of bytes in the other paired port's input queue. It looks as though `tty_insert_flip_string()` is the way to write bytes into the other paired port's input queue. But I can't see a function that will give me a count of bytes in the other paired port's input queue. Do you have any advice on this?

**Comment by stappersg** [comment]
> scenario where the application connected to the other paired port can only read data at a certain rate

https://en.wikipedia.org/wiki/RS-232#RTS,_CTS,_and_RTR a.k.a.  hardware flow control.


@cmcqueen consider to close this issue to prevent it consumes further human energy. (Yes, open issues do have some costs)
