### ISSUE TITLE
modprobe: ERROR: could not insert 'tty0tty': Device or resource busy

### ISSUE THREAD

**Issue by zoltanmaric** [freemed/tty0tty#20]
I can't run the emulator under `4.15.0-32-generic` in Ubuntu 18.04. Here's what I tried:

```bash
cd modules
make
sudo cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc/
sudo depmod
sudo modprobe tty0tty # this fails with "modprobe: ERROR: could not insert 'tty0tty': Device or resource busy"
```
and there are no `tnt*` devices under `/dev/`.

This used to work under `4.15.0-29-generic`, but not under `4.15.0-30-generic` or `4.15.0-32-generic`.

Could you please help me with this?

**Comment by zoltanmaric** [comment]
PEBCAK

Sorry, I cloned both this repository and lcgamboa/tty0tty, and I was attempting to perform the steps in the other one instead of this one. The steps above work just fine with `4.15.0-32-generic`. I'm closing the issue.

**Comment by waageesh** [comment]
I am also getting same issues, below is the traceback, could you please check and tell where is the issue ?

===================================================================
waageesh@waageesh-Aspire-A715-75G:~/Downloads/Softwares/tty0tty$ hostnamectl
   Static hostname: waageesh-Aspire-A715-75G
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 7a93dcb479364111a24c53faca24ad60
           Boot ID: f50dc5d4059f49ca9bcabbf3e677ea32
  Operating System: Ubuntu 20.04.2 LTS
            Kernel: Linux 5.8.0-48-generic
      Architecture: x86-64

===================================================================

![image](https://user-images.githubusercontent.com/16902073/113469813-4206fe00-946e-11eb-9241-92a44f8f41ad.png)


![image](https://user-images.githubusercontent.com/16902073/113469827-577c2800-946e-11eb-972f-9f0b32fd7794.png)

**Comment by stappersg** [comment]
Link to #32
