### ISSUE TITLE
tty_port_destroy was added in 3.8.1.

### ISSUE THREAD

**Issue by mcampin** [freemed/tty0tty#22]
The following in tty0tty.c is wrong. It should be 3.8.

#if LINUX_VERSION_CODE >= KERNEL_VERSION(3,7,0)
		tty_port_destroy(&tport[i]);
#endif

Also, why isn't this function being called if tty_register_driver fails? The tty_port_destroy comment in tty_port.c is:

 * When a port was initialized using tty_port_init, one has to destroy the
 * port by this function. Either indirectly by using tty_port refcounting
 * (tty_port_put) or directly if refcounting is not used.

**Comment by stappersg** [comment]
@mcampin 
> ... It should be ...

Please convert that to a _pull request_ and see what happens.
