### ISSUE TITLE
Installation steps on fedora 27

### ISSUE THREAD

**Issue by papapel** [freemed/tty0tty#24]
Thank you for this works. Please find below the steps I followed to install that on Fedora 27:

``` bash
su -c 'dnf install kernel-devel'
sudo dnf install elfutils-libelf-devel
git clone https://github.com/freemed/tty0tty
cd tty0tty/module
make
(root) cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc/
(root) depmod
(root) modprobe tty0tty
(root) chmod 666 /dev/tnt*
ls -la /dev/tnt*
```

Fedora documentation to know more about requirements to build kernel modules: https://fedoraproject.org/wiki/Building_a_custom_kernel#Building_Only_Kernel_Modules_.28Out_Of_Tree_Modules.29

**Comment by stappersg** [comment]
I see no reason to keep this issue open.
