### ISSUE TITLE
modprobe: ERROR: could not insert 'tty0tty': Device or resource busy

### ISSUE THREAD

**Issue by waageesh** [freemed/tty0tty#32]
I am also getting same issues, below is the traceback, could you please check and tell where is the issue ?

===================================================================
waageesh@waageesh-Aspire-A715-75G:~/Downloads/Softwares/tty0tty$ hostnamectl
Static hostname: waageesh-Aspire-A715-75G
Icon name: computer-laptop
Chassis: laptop
Machine ID: 7a93dcb479364111a24c53faca24ad60
Boot ID: f50dc5d4059f49ca9bcabbf3e677ea32
Operating System: Ubuntu 20.04.2 LTS
Kernel: Linux 5.8.0-48-generic
Architecture: x86-64

===================================================================

![image](https://user-images.githubusercontent.com/16902073/113469871-ad50d000-946e-11eb-8175-393e4f1cac70.png)

![image](https://user-images.githubusercontent.com/16902073/113469879-b9d52880-946e-11eb-919e-20d6cca64c66.png)

**Comment by stappersg** [comment]
Please report what happens upon
```
sudo insmod /path/to/tty0tty.ko
```

**Comment by waageesh** [comment]
![image](https://user-images.githubusercontent.com/16902073/113470429-310cbb80-9473-11eb-95a0-de92d312461d.png)

**Comment by stappersg** [comment]
On Fri, Apr 02, 2021 at 11:23:44PM -0700, waageesh wrote:
> ![image](https://user-images.githubusercontent.com/16902073/113470429-310cbb80-9473-11eb-95a0-de92d312461d.png)
> 

And why should I leave my text based mail client
to visit a picture with text?

In other words:
Please send the report on
```
sudo insmod /path/to/tty0tty.ko
```

In case the quick response of original poster was saying something
like "No, still no success. I'm now active waiting, hurry up". This
advice http://www.catb.org/~esr/faqs/smart-questions.html#intro

**Comment by waageesh** [comment]
This is what i got on ```sudo insmod /path/to/tty0tty.ko```

```
waageesh@waageesh-Aspire-A715-75G:~/Downloads/Softwares/tty0tty/module$ sudo insmode tty0tty.ko 
sudo: insmode: command not found
```

**Comment by stappersg** [comment]
On Sat, Apr 03, 2021 at 12:20:44AM -0700, waageesh wrote:
> This is what i got on ```sudo insmod /path/to/tty0tty.ko```
> 
> ```
> ***@***.***Aspire-A715-75G:~/Downloads/Softwares/tty0tty/module$ sudo insmode tty0tty.ko 
> sudo: insmode: command not found
> ```

So write `insmod` as `insmod`,  not as `insmode`.  Drop the `e`.

**Comment by waageesh** [comment]
new error as "operation not permitted error"

```
waageesh@waageesh-Aspire-A715-75G:~/Downloads/Softwares/tty0tty/module$ sudo insmod tty0tty.ko
insmod: ERROR: could not insert module tty0tty.ko: Operation not permitted
```

**Comment by stappersg** [comment]
On Sat, Apr 03, 2021 at 01:17:11AM -0700, waageesh wrote:
> new error as "operation not permitted error"
> 
> ```
> ***@***.***Aspire-A715-75G:~/Downloads/Softwares/tty0tty/module$ sudo insmod tty0tty.ko
> insmod: ERROR: could not insert module tty0tty.ko: Operation not permitted
> ```
> 

https://duckduckgo.com/?q=insmod%3A+ERROR%3A+could+not+insert+module+tty0tty.ko%3A+Operation+not+permitted

**Comment by stappersg** [comment]
For what it is worth: _it works for me_
* compiles cleanly
* allowed to `insmod`

With  `sudo dmesg | tail -n 3` do I get
```
[ 1200.089467] tty0tty: loading out-of-tree module taints kernel.
[ 1200.089561] tty0tty: module verification failed: signature and/or required key missing - tainting kernel
[ 1200.094659] tty0tty null modem driver v1.2
```
And I do enjoy the _dmks_ stuff from https://github.com/freemed/tty0tty/tree/master/debian (Upon new kernels I get new versions of `tty0tty`.)  This is on **Debian**.

I **think** that original poster is being obstructed by some _prevent loading of kernel modules that are not blessed by us_ measures. Such measures are often sold for "security" reasons.


So this issue now waits for updates like
* works for me on distro ...
* no problem here on distro ... version ...
* also got _Operation not permitted_ on distro ... version ...
* also got _Operation not permitted_ and could circumvent it with ...
* at $URL is documented how to cope this, following the process described over there allowed me to do what I want to do. Simply using `tty0tty`.

**Comment by MAKCOFF** [comment]
Sorry, but i have too this problem.
maksim@hp-pc:~$ hostnamectl
   Static hostname: hp-pc
   Pretty hostname: HP-PC
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: 3ed361a1ac9747da880fc9a3e69eb828
           Boot ID: 5196282d9852444184d17048f839c02f
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.13.0-27-generic
      Architecture: x86-64

maksim@hp-pc:~$ sudo depmod
maksim@hp-pc:~$ sudo modprobe tty0tty
modprobe: ERROR: could not insert 'tty0tty': Operation not permitted

maksim@hp-pc:~$ sudo dmesg | tail -n 3
[ 4557.698774] Lockdown: modprobe: unsigned module loading is restricted; see man kernel_lockdown.7
[ 4566.196144] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[ 5034.553279] Lockdown: modprobe: unsigned module loading is restricted; see man kernel_lockdown.7

Help, please

**Comment by stappersg** [comment]
> Lockdown: modprobe: unsigned module loading is restricted; see man kernel_lockdown.7

That is another issue  (that is unrelated to the code base of `tty0tty`).
