### ISSUE TITLE
Not working on Linux kernel 5.12.4-arch1-2

### ISSUE THREAD

**Issue by ark-sandbox** [freemed/tty0tty#34]
ENOTTY received on Linux kernel 5.12.4-arch1-2

openat(AT_FDCWD, "/dev/tnt1", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 10
flock(10, LOCK_EX|LOCK_NB)              = 0
ioctl(10, TIOCEXCL)                     = 0
ioctl(10, TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
ioctl(10, TIOCMGET, [0])                = 0
ioctl(10, TCGETX, 0x55a071c56090)       = -1 ENOTTY (Inappropriate ioctl for device)
close(10)                               = 0

**Comment by stappersg** [comment]
Please elaborate

**Comment by ark-sandbox** [comment]
@stappersg  I recently upgraded Arch based Linux box, suddenly my program reads/writes from tty0tty stopped working.
I assumed this was due to Kernel upgrade made tty0tty driver incompatible. 
After recompiling libserial library with new Linux headers, the issue resolved.
Macro values might be changed for IOCTL commands.
