### ISSUE TITLE
Ubuntu /module/make  error 

### ISSUE THREAD

**Issue by Nileshhampiholi** [freemed/tty0tty#39]
Hello, 

I followed the steps exactly for installation. 
/pts/make works perfectly fine. 

But /module/make throws the following error. 
error: initialization of ‘int (*)(struct tty_struct *)’ from incompatible pointer type ‘unsigned int (*)(struct tty_struct *)’ [-Werror=incompatible-pointer-types]
  603 |  .write_room = tty0tty_write_room,
      |                ^~~~~~~~~~~~~~~~~~

I have ugraded the Kernal and build and also tried re installing them  but the error remains the same
![Screenshot from 2021-11-17 15-23-16](https://user-images.githubusercontent.com/19320161/142218919-9b3a3bf4-1d91-4bd7-b636-168367027e45.png)

**Comment by stappersg** [comment]
On Wed, Nov 17, 2021 at 06:27:00AM -0800, Nilesh Hampiholi wrote:
> 
> ... /module/make throws the following error. 
> error: initialization of ‘int (*)(struct tty_struct *)’ from incompatible pointer type
>  ‘unsigned int (*)(struct tty_struct *)’ [-Werror=incompatible-pointer-types]
>   603 |  .write_room = tty0tty_write_room,
>       |                ^~~~~~~~~~~~~~~~~~

Kernel version?
Compiler version?

**Comment by bg1avd** [comment]
I have same issue at my Ubuntu 18.04.1 system.
![image](https://user-images.githubusercontent.com/16436148/142573963-1b1f08b8-bab9-4485-8461-5ecc77a4e873.png)

**Comment by bg1avd** [comment]
Kernel is 5.4.0-90-generic

**Comment by Nileshhampiholi** [comment]
Compiler - gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Kernel - 5.11.0-40-generic

**Comment by bg1avd** [comment]
try to fix it by change 268 line: static int tty0tty_write_room(struct tty_struct *tty)

**Comment by sniperlucian** [comment]
additional hint to make it more clear:

for me was line 261 and its change from:

`static unsigned int tty0tty_write_room(struct tty_struct *tty)
`
to suggestd:

`static int tty0tty_write_room(struct tty_struct *tty)`

**Comment by ShaneMurphy2** [comment]
@sniperlucian's is what I ended up doing as well. This should probably be fixed right?

**Comment by stappersg** [comment]
> Would probably have to have some Makefile logic for kernels < 5.14.

That did happen in #40
