### ISSUE TITLE
Back/forward compatibility issues

### ISSUE THREAD

**Issue by onurturhan** [freemed/tty0tty#46]
Latest commit tested for newer and older (w.r.t. KERNEL_VERSION(5, 14, 0)) versions and found back/forward compatibility issues for 4 lines below:

After patching lines as below, working older and newer kernel versions.

1. This is a back compatibility issue

=> Now:
https://github.com/freemed/tty0tty/blob/c17271a8eceedd10fdb743990e2551eaac57e9ad/module/tty0tty.c#L635

=> Patch for back compatiblity;
```C
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 14, 0)
	tty0tty_tty_driver = tty_alloc_driver(2 * pairs, 0);
#else
	tty0tty_tty_driver = alloc_tty_driver(2*pairs);
#endif
```

2. This is a back compatibility issue

=> Now:
https://github.com/freemed/tty0tty/blob/c17271a8eceedd10fdb743990e2551eaac57e9ad/module/tty0tty.c#L671

=> Patch for back compatiblity;
```C
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 14, 0)
	tty_driver_kref_put(tty0tty_tty_driver);
#else
	put_tty_driver(tty0tty_tty_driver);
#endif	
```

3.This is a back compatibility issue, but this is also not working for newer versions ('tty0tty_write' could return negative value, but assumed that it should return non-negative value)

=> Now:
https://github.com/freemed/tty0tty/blob/c17271a8eceedd10fdb743990e2551eaac57e9ad/module/tty0tty.c#L217

=>  Patch for back compatiblity  & for newer ( > KERNEL_VERSION(5, 14, 0)) kernel versions,

```C
int retval = -EINVAL;
```

4. This is a back compatibility issue, ('tty0tty_write_room' function now returns (for this line) non-negative for older versions, but should return non-negative for newer kernels, and negative for older versions.)

=>  Now:
```C
	int room = 0;

	if (!tty0tty)
		return -ENODEV;
```
=> Patch for older & newer ( > KERNEL_VERSION(5, 14, 0)) kernel versions,

```C
#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 14, 0)
	int room = -EINVAL;
#else
	int room = 0;
#endif	

	if (!tty0tty) {
#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 14, 0)
            room = -ENODEV
#endif
            return room;
        }
```

**Comment by stappersg** [comment]
This issue now has a link to #37
